DELETE http://localhost:3003/api/blogs/68c19422e16161fba0f58900
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNob2JpIiwiaWQiOiI2OGMxOTJiNTcwMDQ2ZGM2YTUxM2ZhYjkiLCJpYXQiOjE3NTc1MTY5NDF9.mUawfc-mbZdDRjadG376eUnvWp2Xm9nwgxX2NULY7zY