DELETE http://localhost:3003/api/blogs/68be9fe3d7bccab561ebefed
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNob2JpIiwiaWQiOiI2OGJlOWUxYmQ3YmNjYWI1NjFlYmVmYzkiLCJpYXQiOjE3NTc0MzEwMDB9.VJb0jbDwfZAR-DJFCY8MDv3Ofbz5QE7o9jWbgu5Ehww