DELETE http://localhost:3003/api/blogs/68c045dac6691bd5a6ba63f5
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNob2JpIiwiaWQiOiI2OGJlOWUxYmQ3YmNjYWI1NjFlYmVmYzkiLCJpYXQiOjE3NTc0OTgzNDJ9.cyoCuxpT3xUk71Ulrl4gaxbHadw-oUyrAmgh8Mzc5A0